spring:
  datasource:
    url: 'jdbc:h2:file:./employees'
    username: 'pai'
    password: 'pai'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
